// =====================================================================
// Broadcast Types
// Types for broadcast state and camera control
// =====================================================================

/**
 * Camera modes for main feed
 */
export type CameraMode = 'world' | 'onboard' | 'battle' | 'pit_lane' | 'helicopter';

/**
 * Output target for stream
 */
export type OutputTarget = 'youtube' | 'twitch' | 'local';

/**
 * Output stream status
 */
export interface OutputStatus {
    target: OutputTarget;
    isActive: boolean;
    isHealthy: boolean;
    droppedFrames: number;
    latencyMs: number;
    bitrate: number;         // kbps
    uptimeMs: number;
    streamKey?: string;      // masked
}

/**
 * Camera suggestion from AI director
 */
export interface CameraSuggestion {
    id: string;
    type: 'driver' | 'battle' | 'incident' | 'pit_activity' | 'leader';
    targetDriverId?: string;
    targetBattle?: { driverA: string; driverB: string };
    cameraMode: CameraMode;
    reason: string;
    confidence: number;      // 0-100
    priority: 'low' | 'medium' | 'high' | 'critical';
    expiresAt: number;       // epoch ms
    createdAt: number;       // epoch ms
}

/**
 * Replay bookmark for auto-anchoring
 */
export interface ReplayBookmark {
    id: string;
    type: 'overtake' | 'spin' | 'contact' | 'pit_stop' | 'incident' | 'lead_change';
    timestamp: number;       // epoch ms
    driverIds: string[];
    description: string;
    autoGenerated: boolean;
    clipStartMs: number;
    clipEndMs: number;
}

/**
 * Main broadcast state
 */
export interface BroadcastState {
    sessionId: string | null;
    featuredDriverId: string | null;
    featuredBattle: { driverA: string; driverB: string } | null;
    cameraMode: CameraMode;
    cameraLocked: boolean;
    delayMs: number;
    outputs: OutputStatus[];
    aiAggressiveness: number;  // 0-100
    overlayVerbosity: 'minimal' | 'standard' | 'detailed';
    pendingSuggestions: CameraSuggestion[];
    replayBookmarks: ReplayBookmark[];
    isLive: boolean;
}
