// =====================================================================
// Race Status Recommendation Types
// Internal recommendation system — DOES NOT control iRacing flags
// =====================================================================

/**
 * ControlBox internal race statuses.
 * These are recommendations for stewards, NOT in-sim flag controls.
 */
export type RaceStatus =
    | 'GREEN'               // Normal racing conditions
    | 'LOCAL_YELLOW'        // Minor event, contained to area
    | 'FULL_COURSE_YELLOW'  // Major incident, recommend neutralization
    | 'REVIEW'              // Incident requires steward attention
    | 'POST_RACE_REVIEW'    // Flag for post-race investigation
    | 'NO_ACTION';          // Event does not require intervention

export type ConfidenceLevel = 'LOW' | 'MEDIUM' | 'HIGH';

export type RecommendationAction = 'ACCEPT' | 'OVERRIDE' | 'DISMISS' | 'DEFER_TO_POST_RACE';

// Reference to a driver involved in an incident
export interface DriverReference {
    driverId: string;
    driverName: string;
    carNumber: string;
}

// Analysis fact used to justify recommendation
export interface AnalysisFact {
    factor: AnalysisFactor;
    value: string | number;
    weight: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
    description: string;
}

export type AnalysisFactor =
    | 'CAR_COUNT'           // Number of cars involved
    | 'SPEED_DELTA'         // Speed difference at contact
    | 'TRACK_BLOCKAGE'      // Is racing line blocked?
    | 'RECOVERY_STATUS'     // Did cars recover safely?
    | 'TRAFFIC_DENSITY'     // Other cars approaching?
    | 'REENTRY_DANGER'      // Unsafe return to track?
    | 'CONTACT_SEVERITY'    // Force of impact
    | 'INCIDENT_TYPE';      // Type of incident

/**
 * A status recommendation generated by ControlBox.
 * Stewards review and decide whether to accept.
 */
export interface StatusRecommendation {
    id: string;
    sessionId: string;
    timestamp: Date;

    // Recommendation
    recommendedStatus: RaceStatus;
    confidence: ConfidenceLevel;
    reasoning: string;

    // Context
    affectedDrivers: DriverReference[];
    incidentId?: string;
    lapNumber: number;
    sessionTimeMs: number;
    replayTimestamp?: number;

    // Analysis
    severityScore: number;          // 0-100
    analysisFacts: AnalysisFact[];

    // Workflow
    status: 'PENDING' | 'DECIDED';
    decision?: StewardDecision;
}

/**
 * A steward's decision on a recommendation.
 * Logged for audit trail.
 */
export interface StewardDecision {
    recommendationId: string;
    action: RecommendationAction;
    overrideStatus?: RaceStatus;    // Only if action is OVERRIDE
    stewardId: string;
    stewardName: string;
    notes?: string;
    decidedAt: Date;
}

/**
 * Timeline event for race audit log.
 */
export interface RaceStatusEvent {
    id: string;
    timestamp: Date;
    type: 'STATUS_CHANGE' | 'RECOMMENDATION' | 'DECISION';
    previousStatus?: RaceStatus;
    newStatus?: RaceStatus;
    recommendation?: StatusRecommendation;
    decision?: StewardDecision;
}

/**
 * Post-race summary of recommendations and decisions.
 */
export interface RecommendationSummary {
    sessionId: string;
    totalRecommendations: number;
    acceptedCount: number;
    overriddenCount: number;
    dismissedCount: number;
    deferredCount: number;
    recommendations: StatusRecommendation[];
    statusTimeline: RaceStatusEvent[];
}

// Status display configuration
export const STATUS_DISPLAY: Record<RaceStatus, { label: string; color: string; icon: string }> = {
    GREEN: { label: 'Green (Normal Racing)', color: 'bg-green-500', icon: '🟢' },
    LOCAL_YELLOW: { label: 'Local Yellow (Contained)', color: 'bg-yellow-400', icon: '🟡' },
    FULL_COURSE_YELLOW: { label: 'Full Course Yellow', color: 'bg-yellow-500', icon: '🟨' },
    REVIEW: { label: 'Under Review', color: 'bg-orange-500', icon: '🔍' },
    POST_RACE_REVIEW: { label: 'Post-Race Review', color: 'bg-purple-500', icon: '⏳' },
    NO_ACTION: { label: 'No Action Required', color: 'bg-slate-500', icon: '✓' },
};

export const CONFIDENCE_DISPLAY: Record<ConfidenceLevel, { label: string; bars: number }> = {
    LOW: { label: 'Low Confidence', bars: 2 },
    MEDIUM: { label: 'Medium Confidence', bars: 5 },
    HIGH: { label: 'High Confidence', bars: 8 },
};
