// =====================================================================
// PDF Report Generator Tests
// Unit tests for report generation functions
// =====================================================================

import { describe, it, expect, vi } from 'vitest';
import {
    generateHTMLReport,
    generateResultsCSV,
    type ReportData,
} from './pdf-report';

const mockReportData: ReportData = {
    sessionInfo: {
        name: 'Round 5 - British GP',
        trackName: 'Silverstone',
        date: new Date('2024-07-07'),
        sessionType: 'Race',
        laps: 52,
        duration: '1:32:45',
    },
    results: [
        {
            position: 1,
            carNumber: '1',
            driverName: 'Max Verstappen',
            team: 'Red Bull Racing',
            laps: 52,
            gap: '+0.000',
            points: 25,
        },
        {
            position: 2,
            carNumber: '44',
            driverName: 'Lewis Hamilton',
            team: 'Mercedes',
            laps: 52,
            gap: '+3.482',
            points: 18,
        },
        {
            position: 3,
            carNumber: '16',
            driverName: 'Charles Leclerc',
            team: 'Ferrari',
            laps: 52,
            gap: '+7.891',
            points: 15,
        },
    ],
    incidents: [
        {
            id: 'inc-1',
            lap: 12,
            type: 'contact',
            drivers: '#44, #1',
            severity: 'light',
            status: 'reviewed',
            decision: 'Racing incident',
        },
    ],
    penalties: [
        {
            driver: 'Sergio Perez',
            carNumber: '11',
            type: 'time_penalty',
            value: '5 seconds',
            reason: 'Causing a collision',
        },
    ],
    recommendations: [
        {
            lap: 12,
            status: 'REVIEW',
            confidence: 'MEDIUM',
            action: 'DISMISSED',
            steward: 'Head Steward',
        },
    ],
};

describe('PDF Report Generator', () => {
    describe('generateHTMLReport', () => {
        it('should generate valid HTML', () => {
            const html = generateHTMLReport(mockReportData);

            expect(html).toContain('<!DOCTYPE html>');
            expect(html).toContain('</html>');
        });

        it('should include session info', () => {
            const html = generateHTMLReport(mockReportData);

            expect(html).toContain('Silverstone');
            expect(html).toContain('Race');
            expect(html).toContain('52');
        });

        it('should include race results', () => {
            const html = generateHTMLReport(mockReportData);

            expect(html).toContain('Race Results');
            expect(html).toContain('Max Verstappen');
            expect(html).toContain('Lewis Hamilton');
            expect(html).toContain('Charles Leclerc');
        });

        it('should include results with positions', () => {
            const html = generateHTMLReport(mockReportData);

            // Check positions are present
            expect(html).toContain('>1<');
            expect(html).toContain('>2<');
            expect(html).toContain('>3<');
        });

        it('should include incidents section', () => {
            const html = generateHTMLReport(mockReportData);

            expect(html).toContain('Incidents');
            expect(html).toContain('contact');
            expect(html).toContain('#44, #1');
        });

        it('should include penalties section', () => {
            const html = generateHTMLReport(mockReportData);

            expect(html).toContain('Penalties');
            expect(html).toContain('Sergio Perez');
            expect(html).toContain('5 seconds');
        });

        it('should include steward decisions', () => {
            const html = generateHTMLReport(mockReportData);

            expect(html).toContain('Steward Decisions');
            expect(html).toContain('DISMISSED');
        });

        it('should include footer with timestamp', () => {
            const html = generateHTMLReport(mockReportData);

            expect(html).toContain('Generated by ControlBox');
            expect(html).toContain('internal report');
        });

        it('should handle empty incidents array', () => {
            const dataWithNoIncidents = {
                ...mockReportData,
                incidents: [],
            };

            const html = generateHTMLReport(dataWithNoIncidents);

            expect(html).not.toContain('Incidents</h2>');
        });

        it('should handle empty penalties array', () => {
            const dataWithNoPenalties = {
                ...mockReportData,
                penalties: [],
            };

            const html = generateHTMLReport(dataWithNoPenalties);

            expect(html).not.toContain('Penalties</h2>');
        });
    });

    describe('generateResultsCSV', () => {
        it('should generate valid CSV with headers', () => {
            const csv = generateResultsCSV(mockReportData.results);

            const lines = csv.split('\n');
            expect(lines[0]).toBe('Position,Car Number,Driver,Team,Laps,Gap,Points');
        });

        it('should include all results', () => {
            const csv = generateResultsCSV(mockReportData.results);

            expect(csv).toContain('Max Verstappen');
            expect(csv).toContain('Lewis Hamilton');
            expect(csv).toContain('Charles Leclerc');
        });

        it('should properly quote values', () => {
            const csv = generateResultsCSV(mockReportData.results);

            expect(csv).toContain('"Max Verstappen"');
            expect(csv).toContain('"Red Bull Racing"');
        });

        it('should handle empty team', () => {
            const resultsWithNoTeam = [
                {
                    position: 1,
                    carNumber: '1',
                    driverName: 'Test Driver',
                    laps: 50,
                    gap: '+0.000',
                    points: 25,
                },
            ];

            const csv = generateResultsCSV(resultsWithNoTeam);

            // Should have empty quoted field for team
            expect(csv).toContain('""');
        });

        it('should produce correct number of rows', () => {
            const csv = generateResultsCSV(mockReportData.results);
            const lines = csv.split('\n');

            // 1 header + 3 data rows
            expect(lines).toHaveLength(4);
        });
    });
});
